const STAGED_SCALE_MULTIPLIER_MIN = 0.1
const STAGED_SCALE_MULTIPLIER_MAX = 1000
const STAGED_SCALE_MULTIPLIER_LOW_BREAK = 2
const STAGED_SCALE_MULTIPLIER_MID_BREAK = 25

export const STAGED_SCALE_MULTIPLIER_TRACK_MIN = 0
export const STAGED_SCALE_MULTIPLIER_TRACK_MAX = 100
export const STAGED_SCALE_MULTIPLIER_TRACK_STEP = 0.1
export const STAGED_SCALE_MULTIPLIER_TRACK_LOW_BREAK = 25
export const STAGED_SCALE_MULTIPLIER_TRACK_MID_BREAK = 50

const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value))

export const resolveStagedScaleMultiplierTrackValue = (scaleMultiplier: number) => {
  const clampedMultiplier = clamp(
    scaleMultiplier,
    STAGED_SCALE_MULTIPLIER_MIN,
    STAGED_SCALE_MULTIPLIER_MAX,
  )

  if (clampedMultiplier <= STAGED_SCALE_MULTIPLIER_LOW_BREAK) {
    return (
      ((clampedMultiplier - STAGED_SCALE_MULTIPLIER_MIN) /
        (STAGED_SCALE_MULTIPLIER_LOW_BREAK - STAGED_SCALE_MULTIPLIER_MIN)) *
      STAGED_SCALE_MULTIPLIER_TRACK_LOW_BREAK
    )
  }

  if (clampedMultiplier <= STAGED_SCALE_MULTIPLIER_MID_BREAK) {
    return (
      STAGED_SCALE_MULTIPLIER_TRACK_LOW_BREAK +
      ((clampedMultiplier - STAGED_SCALE_MULTIPLIER_LOW_BREAK) /
        (STAGED_SCALE_MULTIPLIER_MID_BREAK - STAGED_SCALE_MULTIPLIER_LOW_BREAK)) *
        (STAGED_SCALE_MULTIPLIER_TRACK_MID_BREAK - STAGED_SCALE_MULTIPLIER_TRACK_LOW_BREAK)
    )
  }

  return (
    STAGED_SCALE_MULTIPLIER_TRACK_MID_BREAK +
    ((clampedMultiplier - STAGED_SCALE_MULTIPLIER_MID_BREAK) /
      (STAGED_SCALE_MULTIPLIER_MAX - STAGED_SCALE_MULTIPLIER_MID_BREAK)) *
      (STAGED_SCALE_MULTIPLIER_TRACK_MAX - STAGED_SCALE_MULTIPLIER_TRACK_MID_BREAK)
  )
}

export const resolveStagedScaleMultiplierFromTrackValue = (trackValue: number) => {
  const clampedTrackValue = clamp(
    trackValue,
    STAGED_SCALE_MULTIPLIER_TRACK_MIN,
    STAGED_SCALE_MULTIPLIER_TRACK_MAX,
  )

  if (clampedTrackValue <= STAGED_SCALE_MULTIPLIER_TRACK_LOW_BREAK) {
    return (
      STAGED_SCALE_MULTIPLIER_MIN +
      (clampedTrackValue / STAGED_SCALE_MULTIPLIER_TRACK_LOW_BREAK) *
        (STAGED_SCALE_MULTIPLIER_LOW_BREAK - STAGED_SCALE_MULTIPLIER_MIN)
    )
  }

  if (clampedTrackValue <= STAGED_SCALE_MULTIPLIER_TRACK_MID_BREAK) {
    return (
      STAGED_SCALE_MULTIPLIER_LOW_BREAK +
      ((clampedTrackValue - STAGED_SCALE_MULTIPLIER_TRACK_LOW_BREAK) /
        (STAGED_SCALE_MULTIPLIER_TRACK_MID_BREAK - STAGED_SCALE_MULTIPLIER_TRACK_LOW_BREAK)) *
        (STAGED_SCALE_MULTIPLIER_MID_BREAK - STAGED_SCALE_MULTIPLIER_LOW_BREAK)
    )
  }

  return (
    STAGED_SCALE_MULTIPLIER_MID_BREAK +
    ((clampedTrackValue - STAGED_SCALE_MULTIPLIER_TRACK_MID_BREAK) /
      (STAGED_SCALE_MULTIPLIER_TRACK_MAX - STAGED_SCALE_MULTIPLIER_TRACK_MID_BREAK)) *
      (STAGED_SCALE_MULTIPLIER_MAX - STAGED_SCALE_MULTIPLIER_MID_BREAK)
  )
}
